##### experiment wide
name: '20210421'
iterations: 100 # by default should be 30
seed: 13

##### data specific
dataset_name: 'dorn231'
dataset: 'data/DORN_env_phy_231_swls_ext.csv'
dataset_survey: 'data/DORN_qns_swls_ext.csv'
dataset_type: 'sensor' # 'sensor', 'sensor_qns'
target_column: 'thermal_cozie'
target_values:
    - 9.0
    - 10.0 
    - 11.0
train_test_ratio: 0.8
test_user_data: 1 # 1, 0.5, 0.25, 0.125, 0.0625
categorical_features: # NOTE: can be update accordingly
    - 'sex'
    - 'clothing'
feedback_sim: 'feedback-dist' # 'feedback-dist', 'baseline'
qns_encoding_idx: [] # NOTE: can be update accordingly
qns_categories: [] # NOTE: can be updated accordingly
worst_cluster: False
gamma: 0.0
divergence: 'jensen-shannon' 
qns_sim: 'cosine' # 'cosine', 'euclidean'
model: 'rdf' # 'rdf', 'xgb'
scorer: 'f1_micro' # 'f1_micro'
use_val: False

# cohort creation
coefficients: # can take plenty different values
    - 0.33 # alpha
    - 0.33 # beta
    - 0.33 # gamma
cluster_algo: 'spectral' # 'spectral', 'kprototype'
cluster_num: 2 # can take many different values
cluster_forced: 'swls' # '-1': data-driven, column_name: based on median value of the column
cluster_assign: 'questions' # 'performance', 'questions'
cluster_predict_criteria: 'cold' # 'warm', 'cold'

# PCM pre-computed makes experiment runs faster
precomputed_pcm: True # by default should be True

# aux debugging
precomputed_test_users: False # by default should be False
